### ISSUE TITLE
what is the real-world use-case for this module

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge-sqlite#1]
This is to confirm my understanding of this modules(sorry if this is naive).  What I understand from the devdoc folder, this module basically offers an SQLite database to other modules. Other modules could execute SQL queries on need. To rephrase, this module avoids the need to link to SQLite library in other modules. Other modules still need to frame the appropriate SQL queries. Nothing more. Nothing less.

I was looking for a module which offers disk persistence( azure-iot-sdk-c offers in-memory network retries, but data is lost on power loss ). If I have to re-use the functionality in this module, then my Modbus module should have SQL queries to INSERT and my iothub module must have queries to SELECT/DELETE(cleanup) from this module. Is that a fair understanding?

**Comment by stephenctw** [comment]
Very sorry that I didn't constantly check the repo. All your understanding is correct. To answer the question in your topic, our original idea is to offer a interface to manipulate SQLite databases from other modules or cloud. It could be used as local buffering or any other purpose if applicable.

Thank.

**Comment by yphuangms** [comment]
Please fork or clone the code for further modification/customization to build module that full fill your need.
This repository is no longer being actively maintained and will be archived. Open issues will be closed.
