### ISSUE TITLE
Filter for a specific ID

### ISSUE THREAD

**Issue by Ilheu** [Azure/iot-edge-sqlite#12]
I'm trying to make a query where I need to select a specific Id, is it possible? Or when I filter data from a table I receive everything?

Something like in SQL:
select Id , Value from test where Id is 123;

Is there any documentation where I can see the commands I can make besides insert and filter? Maybe a "update" or "delete"....

**Comment by yphuangms** [comment]
Please fork or clone the code for further modification/customization to build module that full fill your need.
This repository is no longer being actively maintained and will be archived. Open issues will be closed.
