### ISSUE TITLE
Default deployment using Marketplace fails

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iot-edge-sqlite#4]
I try to deploy the module as created by the Azure IoT Edge MArketplace deployment. This is the result:

> uno2271gsv@uno2271g2sv-UNO-2271G-E2xAE:/app/db$ sudo iotedge logs -f SQLite
IoT Hub module client initialized.
Desired property change:
{"SQLiteConfigs":{"Db01":{"DbPath":"/app/db/test.db","Table01":{"TableName":"test","Column01":{"ColumnName":"Id","Type":"numeric","IsKey":"true","NotNull":"true"},"Column02":{"ColumnName":"Value","Type":"numeric","IsKey":"false","NotNull":"true"}}}},"$version":1}
Attempt to load configuration: {"SQLiteConfigs":{"Db01":{"DbPath":"/app/db/test.db","Table01":{"TableName":"test","Column01":{"ColumnName":"Id","Type":"numeric","IsKey":"true","NotNull":"true"},"Column02":{"ColumnName":"Value","Type":"numeric","IsKey":"false","NotNull":"true"}}}},"$version":1}
Exception while opening database, err message: SQLite Error 14: 'unable to open database file'.
Check if the database file is created or being mounted into the conainter correctly

I tried to create the /app/db folder using sudo rights but this did not change a thing. Neither did giving the folder more rights or creating an empty file with the right filename.

What is happening?

**Comment by LeivoSepp** [comment]
Hello.
I have exactly same error message. This module doesn't work.
Environment: Raspberry PI, Raspian and IoT Edge. Latest versions.
How can I get this working? 
Is there any other solution to keep the data? Any NoSQL DB for IoT Edge?

**Comment by sandervandevelde** [comment]
I have got it running later on. See [my blog](https://sandervandevelde.wordpress.com/2019/01/13/integrating-sqlite-in-azure-iot-edge-for-local-storage/) for more information. We switched over to the Sql Server module afterwards.

**Comment by LeivoSepp** [comment]
Thanks @sandervandevelde .
I am running the solution on Raspberry PI and I found that the SQL Server is only 64bit image. I need some db for running in ARM32.

**Comment by sandervandevelde** [comment]
Closed it.
