### ISSUE TITLE
Update to new 1.0.7 requirements

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iot-edge-sqlite#6]
IoT Edge 1.0.7 arrived a few weeks ago: https://azure.microsoft.com/en-au/updates/iot-edge1-0-7/ 

> To get these changes, be sure to update your modules to use the 1.20 version of the client SDK in addition to using the latest version of the runtime.

Please update this module.

**Comment by yphuangms** [comment]
Please fork or clone the code for further modification/customization to build module that full fill your need.
This repository is no longer being actively maintained and will be archived. Open issues will be closed.
