### ISSUE TITLE
How to run the module on Windows 10 IoT Enterprise (Win 10)

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iot-edge-sqlite#7]
I want to run the sqlite module with Windows 10 IoT Enterprise (Win 10 1809 LTS). I make use of Windows containers.

I tried with URI:

    mcr.microsoft.com/azureiotedge/sqlite:1.0.5-win10-amd64-1809

Container create options:

    {
      "HostConfig": {
        "Binds": [
          "C:\\iotsqlite:c:\\app"
        ]
      }
    }

(With full access for everyone to the exiting folder on host)

and desired properties:

    "properties": {
      "desired": {
        "SQLiteConfigs": {
          "Db01": {
            "DbPath": "test.db",
           ....

(so there is no path in here)

But this set of settings (and many other combinations) all failed.

Can you provide the correct Windows containers on Windows LTS 1809 setup for the sqlite module which is also available in the iot edge module store?

Regards,

Sander

**Comment by yphuangms** [comment]
Hi @sandervandevelde ,

One of the configuration issue I can see is that you bind this folder "c:\app" from container to an external volume, where "c:\app" is where the main program and dll are stored. Ididn't try this, but I suspect, If you bind it to external volume, either the binding will fail (your db file won't be mapped to external volume), or all the SQLite main program and dlls are gone because the folder is forced to be mapped to external volume. To be safe, map the external volume (on host) to an folder (in container) which is not in use.

Please try following module configuration:

Container create options:
```
{
  "HostConfig": {
    "Binds": [
      "C:\\iotsqlite:c:\\db"
    ]
  }
}
```
and desired properties:
```
"properties": {
  "desired": {
    "SQLiteConfigs": {
      "Db01": {
        "DbPath": "/db/test.db",
       ....
```

If you still cannot bring up module successfully, and you can see the log shows failure at connection timeout, please verify if "Simulated Temperature Sensor" module encounter the same issue, if so, it could be the name resolving issue between container to host. Then, please modify iotedge config to specify a container network for your modules.

In c:\ProgramData\iotedge\config.yaml:
```
moby_runtime:
  uri: 'npipe://./pipe/iotedge_moby_engine'
  network: "azure-iot-edge"
```

**Comment by sandervandevelde** [comment]
I tested this on Windows 10 1809 LTS with Moby (iotedge 1.0.9)

The database was created on my local host folder:
![afbeelding](https://user-images.githubusercontent.com/694737/80597266-e0e9d580-8a27-11ea-9c6b-e233acf690f9.png)

And the log shows it can access the database:

![afbeelding](https://user-images.githubusercontent.com/694737/80597452-24444400-8a28-11ea-987a-e3fed93f1640.png)

The database creation seems to work fine now.

The module needs maintenace though (like the 1.0.7 changes, update of nuget packages, 'old' usage of AmqpTransport setting where Mqtt is the default in the latest C# module template, a possible memory leak with 'new Message()' (see the latest C# module template for fix with 'using'), and more elaborate logging message in case of misconfiguration).

Thanks for showing how the binding and desired properties have to be configured for Windows,

**Comment by amideveloper** [comment]
Hi @sandervandevelde,
I am trying to use the sqlite module in one of my application and am doing the development in Visual studio 2019. I am trying to send data and read data from my custom modules.

I have added the SQLite module from the market place and updated the configurations as below.
   "image": "mcr.microsoft.com/azureiotedge/sqlite:1.0.5-win10-amd64-1809",
              "createOptions": {
                "HostConfig": {
                  "Binds": [
                    "C:\\iotsqlite:c:\\db"
                  ]
                }
              }


And the desired property config looks like below:

  "SQLiteConfigs": {
          "Db01": {
            "DbPath": "/db/testlocdb.db",
        .....

I have added the folder and set all the permissions. Still when i ran these module from Visual studio, i couldn't see any database file created on the path configured. At times, i get build error which states as iotedgeserver is external skipping.

Additional information:
My docker container is set to run on Linux container. If i switch to Windows container, fails at sqlite image fetching operation.

Please let me know if am missing anything on configuration.

**Comment by sandervandevelde** [comment]
In Linux you have to give the folder on the host filesystem elevated rights but you are using Windows.

I see the Linux style db path in the desired properties while using Windows. Can you rewrite that to a Windows path?

**Comment by amideveloper** [comment]
@sandervandevelde 

Am getting below error when i switched to windows container. Any idea?

1>no such image: mcr.microsoft.com/azureiotedge/sqlite:1.0:1.0.5-win10-amd64-1809: invalid reference format
1>ERROR: Error while executing command: docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml up -d. Command '['docker-compose', '-f', 'C:\\ProgramData\\iotedgehubdev\\data\\data\\docker-compose.yml', 'up', '-d']' returned non-zero exit status 1.

**Comment by amideveloper** [comment]
@sandervandevelde 

Tried with the below path but no luck!

  "DbPath": "C:\\db\\testlocdb.db",

**Comment by yphuangms** [comment]
@amideveloper 
Have you enable file sharing in "Docker for Windows" settings? 
You will need to grant the access to "Docker for Windows" to share you windows drive to docker.
https://stackoverflow.com/questions/51816407/how-to-set-the-shared-drives-in-docker-for-windows

**Comment by sandervandevelde** [comment]
And try a relative path too

**Comment by amideveloper** [comment]
@yphuangms 
That is required for the linux container. For windows that options are not there.

**Comment by amideveloper** [comment]
@sandervandevelde  I tried using relative path too.  When i checked on the log on docker runtime 
I have the below error message only. Eventhough i updated the path it still shows the default one.

{"SQLiteConfigs":{"Db01":{"DbPath":"/app/db/test.db","Table01":{"TableName":"test","Column01":{"ColumnName":"Id","Type":"numeric","IsKey":"true","NotNull":"true"},"Column02":{"ColumnName":"Value","Type":"numeric","IsKey":"false","NotNull":"true"}}}},"$version":2}

Attempt to load configuration: {"SQLiteConfigs":{"Db01":{"DbPath":"/app/db/test.db","Table01":{"TableName":"test","Column01":{"ColumnName":"Id","Type":"numeric","IsKey":"true","NotNull":"true"},"Column02":{"ColumnName":"Value","Type":"numeric","IsKey":"false","NotNull":"true"}}}},"$version":2}

Exception while opening database, err message: SQLite Error 14: 'unable to open database file'.

Check if the database file is created or being mounted into the conainter correctly

**Comment by sandervandevelde** [comment]
I compared your path with what I have tested:

These are the create options:
```
{
  "HostConfig": {
    "Binds": [
      "C:\\iotsqlite:c:\\db"
    ]
  }
}
```
(Note the double backslashes)

and desired properties:

```
"properties": {
  "desired": {
    "SQLiteConfigs": {
      "Db01": {
        "DbPath": "/db/test.db",
       ....
```

Can you test it with this specific combination?

**Comment by amideveloper** [comment]
@sandervandevelde  No luck :-(

**Comment by yphuangms** [comment]
Please fork or clone the code for further modification/customization to build module that full fill your need.
This repository is no longer being actively maintained and will be archived. Open issues will be closed.
