### ISSUE TITLE
Sending incorrect SQL query to SQLite causes infinite crash loop

### ISSUE THREAD

**Issue by Shacotaco** [Azure/iot-edge-sqlite#9]
Sending an incorrect SQL query message crashes SQLite before it can send a message received confirmation to the edgeHub. The edge agent then restarts the SQLite module and the edgeHub (not having received any message confirmation) resends the same incorrect SQL query message to SQLite, making it crash again. This makes the SQLite module end up in an infinite crash loop unless the messages are cleared from edgeHub.

In my case I had a typo in the select query table name and forgot to add ';' at the end of the query.

See below image with error in edgehub
![afbeelding](https://user-images.githubusercontent.com/10940387/83799494-2db77080-a6a6-11ea-96ce-5fa10149455b.png)

**Comment by yphuangms** [comment]
Please fork or clone the code for further modification/customization to build module that full fill your need.
This repository is no longer being actively maintained and will be archived. Open issues will be closed.
